In [3]:
first_name = "john"
last_name = "doe"
print(first_name + last_name)

johndoe


In [4]:
first_name = "john"
last_name = "doe"
print(first_name + " "+ last_name)

john doe


In [7]:
first_name = "john"
last_name = "doe"
full_name = first_name + last_name
print ( full_name )

johndoe


In [8]:
x = 5
x = 6
print(x)

6


In [1]:
a = 6
b=4
print(a**b)

1296


In [2]:
w=6
e=4
f=4**2
print(w/f)

0.375


In [3]:
w=6
e=4
f=4**2
b=w/f
print(b)

0.375


In [7]:
w=6
e=4
b=w/e**2
print(b)

0.375


In [9]:
a=4
type (a)

int

In [10]:
x=4
y=3
x==y

False

In [11]:
x=4
y=6
x==y

False

In [14]:
x=4
y=6
x and y

6

In [15]:
x=10
y=4
x or y

10

In [16]:
x=4
y=6
x or y

4

In [17]:
x=4
y=7
not y

False

In [19]:
x=7
y=7
not x

False

In [27]:
print("iamdon")

iamdon


In [32]:
print("i am don")

i am don


In [33]:
product_1= 5*250
product_2= 25*656
product_3=34*274
print("the price of prodcut 1 is ",product_1)
print("the price of prodcut 2 is ",product_2)
print("the price of prodcut 3 is ",product_3)
print("the total price is ",product_1+product_2+product_3)

the price of prodcut 1 is  1250
the price of prodcut 2 is  16400
the price of prodcut 3 is  9316
the total price is  26966


In [36]:
p=1500000
r=0.08
t=3
s=(p*r*t)/100
x=120000
print("the simple interest is ",s)
x==p*r*t

the simple interest is  3600.0


False

In [37]:
r=12
pi=3.14
R=r**2
area=pi*R
print("the area of the circle is ",area)

the area of the circle is  452.16


In [2]:
x=4
c=float(x)
print("the value is  ",c)

the value is   4.0


In [3]:
print(type(c))

<class 'float'>


In [4]:
print("the class is ", type(c))

the class is  <class 'float'>


In [5]:
a="6.3"
print(float(a))

6.3


In [6]:
a="6.3"
print(a)

6.3


In [7]:
a=5.4563839
c=int(a)
print(c)

5


In [14]:
a=20
d=str(a)
c="2"
print(a+2)

22


In [17]:
c="+91 "
n=9108684409
b=str(n)
print(c+b)

+91 9108684409


In [19]:
c=4.779
print(abs(c))

4.779


In [22]:
c=4
print(abs(c))

4


In [27]:
p=250000
r=9.34567
t=3
simple_interest= (p*r*t)/100
print("the simple interest is ", int(simple_interest))

the simple interest is  70092


In [28]:
b=100
binary=bin(b)
print("the binary rep for no 100 would be ",binary)

the binary rep for no 100 would be  0b1100100


In [29]:
d=[6,9,4,5,6,7,8,0]
print('the sum of the above list is', sum(d))

the sum of the above list is 45


In [30]:
e=(4,5,6,7,8,9)
sum(e)

39

In [42]:
a=[5,10,15,20]
d=sum(a,10)
d

60

In [43]:
q=5
e=8
operation="q*e"
eval(operation)

40

In [45]:
name=input("enter your name-")
print("name entered is ",name)

enter your name- prateek


name entered is  prateek


In [46]:
name=input("your name please;")
age=input("your age please;")
gender=input("your gender;")
print("we have got all the required info",name,age,gender)

your name please; prateek
your age please; 34
your gender; male


we have got all the required info prateek 34 male


In [56]:
x=int(input("enter your no."))
y=int(input("enter another no."))
total=x+y
print("the sum of both the no would be:",total)

enter your no. 5
enter another no. 6


the sum of both the no would be: 11


In [3]:
age=abs(int(input("enter your age")))
weight=int(input("enter your weight"))
height=int(input("enter your height"))
BMR=88.362+(13.397*weight)+(4.799*height)-(5.677*age)
print("the bmr for this individual would be",int(BMR))

enter your age -24
enter your weight 90
enter your height 172


the bmr for this individual would be 1983


In [3]:
x=input("enter the matchematical expression")
auto_evaluate= eval(x)
print("the answer for this expression is",auto_evaluate)

enter the matchematical expression 44*67/22


the answer for this expression is 134.0


In [8]:
house_size_1=float(input("enter the size of the house for user 1"))
bedroom_size_1=float(input("enter the no of bedrooms you want"))
house_size_2=float(input("enter the size of the house for user 2"))
bedroom_size_2=float(input("enter the no of bedrooms you want"))
total_size_1= house_size_1*5000
print("the total size of the user 1 would be",total_size_1)
total_size_2 =house_size_2*5000
print("the total size of the user 2 would be",total_size_2)
threshold=7500000
x=total_size_1>=threshold
y=total_size_2>=threshold
print("the total price for user 1 is exceeding the threshold",x)
print("the total price for user  is exceeding the threshold",y)

enter the size of the house for user 1 300
enter the no of bedrooms you want 2
enter the size of the house for user 2 500
enter the no of bedrooms you want 2


the total size of the user 1 would be 1500000.0
the total size of the user 2 would be 2500000.0
the total price for user 1 is exceeding the threshold False
the total price for user  is exceeding the threshold False


In [15]:
current_price=100
percent_change=10
new_price=current_price*((1+percent_change)/100)
x=float(input("enter your budget"))
y=x>=new_price
print("the budget entered is higher than the new price",y)

enter your budget 100


the budget entered is higher than the new price True


In [21]:
max_temp=100.00
min_temp=10.00
y=float(input("enetr the current temp"))
x=min_temp<=y<=max_temp


print("the current temp lies within the range",x)


enetr the current temp 20


the current temp lies within the range True


In [23]:
temp=float(input("enter the temperature"))
if temp<15:
    print("the temperature is not convinient")
if 24<temp<28:
    print("the temo is convinivent")

enter the temperature 12


the temperature is not convinient


In [25]:
vote=int(input("enter the age"))
if vote>=18:
    print("eligible to vote")
else:
    print("not eligible")

enter the age 11


not eligible


In [35]:
base=float(input("enter your base salary"))
print("the base salary of this employee is",base)
age=int(input("enetr the year of attendance "))
if age>5:
    bonus= (0.08*base)+base
    print("the loyaltybonus would be",bonus)
    tax=(bonus-(0.12*bonus))
    print("the net salary along with the tax deductions would be",tax)
else:
    tax=(base-(0.12*base))
    print("not applicable for a bonus,but the net salary would be",tax)

enter your base salary 100


the base salary of this employee is 100.0


enetr the year of attendance  6


the loyaltybonus would be 108.0
the net salary along with the tax deductions would be 95.04


In [38]:
city=input("enter your city")
if city == "mumbai":
    print("famous monument is gateway of india")
elif city=="bangalore":
    print("famous monument is botanical garden")
elif city=="pune":
    print("famous monument is shanivar vada")
elif city=="kolkata":
    print("famous monument is victoria memorial")
elif city=="chennai":
    print("famous monument is marina beach")
else:
    print("no records found")

enter your city mumbai


famous monument is gateway of india


In [42]:
count=2
while count<=6:
    print(count)
    count=count+1

2
3
4
5
6


In [43]:
n=1
while n<=50:
    if n%2==0:
        print(n)
    n=n+1    

2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50


In [1]:
email=input("enter your email id")
valid_email = False
while  not valid_email:
    if "@" in email and "." in email:
        print("valid email adress")
        valid_email=True
        
    else:
        print("invalid emil")
        email=input("enter email id")

enter your email id PJDIJFI


invalid emil


enter email id PRETEJ@NFUDI.COM


valid email adress


In [2]:
ds="prateek"
for y in ds:
    print(y)

p
r
a
t
e
e
k


In [5]:
for i in range(9,24):
    print(i)


9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [7]:
for i in range(26):
    if i%2==0:
        print(i)
        

0
2
4
6
8
10
12
14
16
18
20
22
24


In [21]:
number=int(input("enter a no brother"))
print("yeh le",number)
          
for i in range(1,11):
           print(f"{number}x{i}={number*i}")


enter a no brother 2


yeh le 2
2x1=2
2x2=4
2x3=6
2x4=8
2x5=10
2x6=12
2x7=14
2x8=16
2x9=18
2x10=20


In [22]:
total_amount= float(input("enter the bill amount"))
if total_amount>=100:
    discounted_price=total_amount-(0.10*total_amount)
    print("your bill would be",discounted_price)
elif 50<total_amount<99.99:
    discounted_price=total_amount-(0.05*total_amount)
    print("your bill would be",discounted_price)
elif total_amount<50:
    print("no discount")

enter the bill amount 299


your bill would be 269.1


In [33]:
num_items=int(input("enter the number of items purchased"))
total_price=0

for i in range(num_items):
    price=float(input("enter the price of the item"))
    total_price=total_price+price
    i+1
if total_price>=100:
    discounted_price=(0.10*total_price)
   
elif 50<total_price<99.99:
    discounted_price=(0.05*total_price)
   
else:
    discounted_price=0
    print("no discount") 
    
subtotal=total_price-discounted_price
print("total bill would be",subtotal)

enter the number of items purchased 3
enter the price of the item 50
enter the price of the item 40
enter the price of the item 10


total bill would be 90.0


In [36]:
for i in range(5):
    if i==3:
        continue
    print(i)
print("i am learning python")    

0
1
2
4
i am learning python


In [39]:
def my_function():
    for i in range(5):
        if i==3:
            continue
        print(i) 

In [40]:
my_function()

0
1
2
4


In [42]:
def bill_amount():
    print("please pay your bill by next suday")
    print("additional fine of rs.500 woud be applied for late payments")

In [43]:
customers=4
for i in range(customers):
    a=input("enter your name kind sir")
    b=int(input("kindy enter the total no of units consumed"))
    total_bill=b*10
    print("the total bill would be ",total_bill)
    bill_amount()

enter your name kind sir prateek
kindy enter the total no of units consumed 500


the total bill would be  5000
please pay your bill by next suday
additional fine of rs.500 woud be applied for late payments


enter your name kind sir pfioa
kindy enter the total no of units consumed jj


ValueError: invalid literal for int() with base 10: 'jj'

In [47]:
def check_even_odd(number):
    if number%2==0:
        print("the no is even")
    else:
        print("odd")

In [48]:
check_even_odd(37)

odd


In [7]:
exam_scores=[85,92,78,90,88,95,82,79,87,91]
def calculate_exam_statistics(exam_scores):
    num_students=len(exam_scores)
    average_score=sum(exam_scores)/num_students
    highest_score=max(exam_scores)
    lowest_score=min(exam_scores)
    num_passed=0
    for score in exam_scores:
        if score>=80:
            num_passed= num_passed+1
    num_failed=num_students-num_passed
    return average_score,highest_score,lowest_score,num_passed,num_failed

       

In [9]:
exam_scores=[85,92,78,90,88,95,82,79,87,91]
average_score,highest_score,lowest_score,num_passed,num_failed= calculate_exam_statistics(exam_scores)
print("the average score is",average_score)
print("the highest is",highest_score)
print("the lowest score is",lowest_score)
print("total students passed", num_passed)
print("total students failed",num_failed)

the average score is 86.7
the highest is 95
the lowest score is 78
total students passed 8
total students failed 2


In [12]:
a=float(input("enter your number"))
square=a**2
print("the square of the number would be",square)

enter your number 3.5


the square of the number would be 12.25


In [6]:
def count_vowels(text):
    vowels="aeiouAEIOU"
    count=0
    for letter in text:
        if letter in vowels:
            count=count+1
    return count
 
    

In [8]:
count_vowels("prateek")

3

In [9]:
count_vowels("tanvi")

2

In [10]:
s=input("enter the name")
x=len(s)
print(x)

enter the name prateek


7


In [11]:
count=len("prateekds12@gmail.com")

In [12]:
print(count)

21


In [13]:
def pass_valid(password):
    has_letter=False
    has_number=False
    has_special=False
    special_char="!@#$%^&*"
    for letter in password:
        if letter.isalpha():
            has_letter=True
        elif letter.isdigit():
            has_number=True
        elif letter in special_char:
            has_special=True
    if has_letter and has_number and has_special:
        return "password is valid"
    else:
        return "not valid"
        



In [14]:
pass_valid("prateeK@11702")

'password is valid'

In [15]:
pass_valid("prbahfhu")

'not valid'

In [18]:
number=input("enter the no.")
total=0
for digit in number:
    total=total+int(digit)
print("the sum would be",total)

enter the no. 234


the sum would be 9


In [24]:
x=int(input("enter the number"))
if x%2==1:
    print("this is a prime no")
else:
    print("not a prime no.")

enter the number 24


not a prime no.


In [28]:
x=int(input("enter the no."))
if x%3==0 or x%5==0:
    print("divisible ")
else:
    print("not divisible")


enter the no. 32


not divisible


In [29]:
def max_number(digit):
    x=max(digit)
    print(x)

In [30]:
max_number(123)

TypeError: 'int' object is not iterable

In [31]:
for i in range(1,5):
    print ("*"*i)

*
**
***
****


In [32]:
def find_max(num1,num2,num3):
    biggest=num1
    if num2>biggest:
        biggest=num2
    if num3>biggest:
        biggest=num3
    return biggest

In [36]:
num1=int(input("enter num1"))
num2=int(input("enter num2"))
num3=int(input("enter num3"))
print("the largest numbr is",find_max(num1,num2,num3))

enter num1 19
enter num2 20
enter num3 3


the largest numbr is 20


In [38]:
def square(num):
    x=num**2
    return x

In [39]:
a=float(input("enter the number"))
print("the square of given number is ",square(a))

enter the number 2


the square of given number is  4.0


In [50]:
def even_numbers(numbers):
    even_number=[]
    for number in numbers:
        if number%2==0:
            even_number.append(number)
    return even_number

In [51]:
numbers_list=[1,2,3,4,5,6,7,8,9]
print("the even numbers here are: ", even_numbers(numbers_list))

the even numbers here are:  [2, 4, 6, 8]


In [61]:
def sum_unique_elements(numbers):
    unique_elements=[]
    total=0
    for number in numbers:
        if number not in unique_elements:
            unique_elements.append(number)
            total=total+number
    return total
    

In [62]:
x=[1,2,3,1,2,3,2,2,3,4,4,5,2,5,6,2]
print("the sum of the uniques elements will be: ",sum_unique_elements(x))

the sum of the uniques elements will be:  21


In [6]:
s=float(input("enter the number"))
if s%3==0 or s%5==0:
    print("the numbmer is disiible")
    

else:
    
    print("not possible")




enter the number 24


the numbmer is disiible


In [8]:
numbers = [10, 45, 23, 89, 67]
largest=numbers[0]
second_largest=numbers[0]
for number in numbers:
    if number>largest:
        second_largest=largest
        largest=number
    elif number<largest and number>second_largest:
        second_largest=number
print("second largest number would be : ",second_largest)

second largest number would be :  67


In [2]:
total=0
numbers=int(input("enter the number: "))
while numbers !=0:
    total=total+numbers
    numbers=int(input("enter the number: "))
print("the sum of the enetred nnumbers are: ",total)
    

enter the number:  7
enter the number:  3
enter the number:  0


the sum of the enetred nnumbers are:  10


In [1]:
x=1
while 1<=x<=20:
    if x%2==0:
        print(x)
    x=x+1
print("done")

2
4
6
8
10
12
14
16
18
20
done


In [2]:
def grade_distribution(grades):
    for marks in grades:
        if 90<marks<100:
            print("a")
        elif 89<marks<90:
            print("b")
        elif 70<marks<79:
            print("c")
        elif 60<marks<69:
            print("d")
        else:
            print("ghar jaa")
    return

In [6]:
grades=[92,4,94,11,56,66,88,78,99,57,77,99]
grade_distribution(grades)

a
ghar jaa
a
ghar jaa
ghar jaa
d
ghar jaa
c
a
ghar jaa
c
a


In [7]:
import random
def  number_guessing_game():
    x=random.randint(1,100)
    print("the random number generated is ",x)
    y=int(input("enter a number player"))
    if y>x:
        print("too high")
    elif y<x:
        print("too low")
    else:
        print("correct guess player,congragulations")

In [10]:
 number_guessing_game()

the random number generated is  62


enter a number player 62


correct guess player,congragulations


In [11]:
def sum_of_squares(n):
    n=int(input("enter the no"))
    x=range(1,n+1)
    total=0
    for i in x:
        total=total+i**2
    return total

In [12]:
sum_of_squares(3)

enter the no 3


14

In [13]:
count=0
while count<5:
    print("hello")
    count+=1

hello
hello
hello
hello
hello


In [17]:
str="i am prateek\n this is my first class"
print(str)

i am prateek
 this is my first class


In [41]:
str="""icknamed "King James",  he is the NBA's
all-time leading scorerand has won four NBA championships from 10 NBA Finals appearances"""
print(str)

icknamed "King James",  he is the NBA's
all-time leading scorerand has won four NBA championships from 10 NBA Finals appearances


In [23]:
a="hello this is alpha one"
print(a[23])

IndexError: string index out of range

In [28]:
a="lebron james"
print(a[-4])



a
m
e
s


In [36]:
a="lebron james"
print((a[-1]),(a[-3]),(a[-2]))

s m e


In [38]:
a="this is very disgusting"
print((a[-1]),(a[-2]),(a[-3]))

g n i


In [39]:
a="i am gonna make my parents proud\n just by working hard"
print(a)

i am gonna make my parents proud
 just by working hard


In [43]:
a="prateek"
print(a[1:3])

ra


In [44]:
a="this is a good boy"
print(a[:])

this is a good boy


In [45]:
a="i am learning"
print(a[0:12:4])

i r


In [47]:
a="less gooo"
print(a[::2])

ls oo


In [49]:
a="this is very disgusting"
print(a[-4:-2])

ti


In [51]:
a="lebron james"
print(a[-4:-1])

ame


In [68]:
def date_of_birth(dates):
    year=int(dates[0:4])
    month=int(dates[5:7])
    day=int(dates[8:])
    x=(input("enter the date"))
    return (year,month,day)

In [71]:
date_of_birth("2026-01-04")

enter the date 2028-87-48


(2026, 1, 4)

In [74]:
a="honesty is the best policy"
print(a[::-1])

ycilop tseb eht si ytsenoh


In [77]:
a="honesty is the best policy"
print(a[::1])

honesty is the best policy


In [84]:
def sub_string(string):
    string=input("enter the string here")
    x=string[3:9]
    return x

In [89]:
sub_string("string")

enter the string here BEST OF LUCK


'T OF L'

In [90]:
s="ARTIFICIAL"
print(s[:-4])


ARTIFI


In [91]:
s="lebronjames"
print(len(s))

11


In [92]:
p="lebron james the goat"
print(len(p))

21


In [94]:
e=input("enter the first name")
f=input("enter the surname")
r=e+" "+f
print(r.upper())

enter the first name prateek
enter the surname sunagad


PRATEEK SUNAGAD


In [95]:
name="prateek sunagad"
king= name.replace("prateek","KING")
print(king)

KING sunagad


In [99]:
sen="i am the best"
print(sen.index("best"))
print(sen.replace("best","bestest"))

9
i am the bestest


In [100]:
r="diujbaehfygyuyaejkfnon"
print(r.find("e"))

6


In [128]:
a="hello"
b="world"
c=a+" "+b
print(c)
print(len(c))
print(c.index("world"))
d=c[6:]
print(d)
g=(d[::-1])
print(g)
e=g.upper()
print(e)
f=e.replace("L","X")
print(f)





hello world
11
6
world
dlrow
DLROW
DXROW


In [130]:
a="world"
print(a[4])

d


In [132]:
a="  python is fun  "
start=0
while a[start]==" ":
    start=start+1
end=len(a)-1
while a[end]==" ":
    end=end-1
new_text=" "
for i in range(start,end+1):
    new_text=new_text+a[i]
print(new_text)

 python is fun


In [134]:
a="prateek"

count=0
for i in a :
    if i=="e":
        
        count=count+1
    else:
        print("0 times")
print(count)

0 times
0 times
0 times
0 times
0 times
2


In [135]:
a="prateek"
print(a[-5:])

ateek


In [136]:
a="prateek"
vowels="aeiouAEIOU"
new_text=" "
for i in a :
    if i not in vowels:
        new_text=new_text+i
print(new_text)

 prtk


In [138]:
a="hkk7947kdm"
new_text=" "
for i in a :
    if i>="0" and i<="9":
        new_text=new_text+i
print(new_text)

 7947


In [145]:
a="prateek"
for i in a:
    print(i)

p
r
a
t
e
e
k


In [148]:
a="kiilldillweioura"
vowel_count=0
cons_count=0
vowels="aeiouAEIOU"
for i in a:
    if i not in vowels:
        cons_count=cons_count+1
    else:
        vowel_count=vowel_count+1
print("total no of vowels are: ",vowel_count)
print("total no of consonants are: ",cons_count)

total no of vowels are:  8
total no of consonants are:  8


In [149]:
a="hello"
empty_text=" "
for i in a:
    if i not in empty_text:
        empty_text=empty_text+i
print(empty_text)

 helo


In [151]:
a="come on man"
print(a.count())

TypeError: count expected at least 1 argument, got 0

In [152]:
text = "python is fun"
words = 0
inside = False

for ch in text:
    if ch != " ":          
        if inside == False:
            words = words + 1
            inside = True
    else:                  
        inside = False

print(words)

3


In [159]:
a=input("enter the sentence")
text=a.split()
longest=" "
for i in text:
    if len(i)>len(longest):
        longest=i
print(longest)

enter the sentence prateek is a good boy


prateek


In [162]:
a=input("enter the sentence")
count=0
word=a.split()
for i in word:
    count=count+1
print("the no of words here are",count)

enter the sentence prateek is  bad


the no of words here are 3


In [161]:
a="prtaeek is bad"
word=a.split()
print(word)

['prtaeek', 'is', 'bad']


In [165]:
a=input("enter the sentence")
w=a.split()
for i in w:
    i[0]=i.upper()
print(i)

enter the sentence prateek is cool


TypeError: 'str' object does not support item assignment

In [171]:
a="hello pyhthon from world"
make_upper= True
new_text=""
for i in a :
    if make_upper and i!= " ":
        new_text=new_text+i.upper()
        make_upper= False
    else:
        new_text=new_text+i
    if i==" ":
        make_upper= True
print(new_text)

Hello Pyhthon From World


In [3]:
p="hello nigger"
make_upper=True
new_text=""
for i in p:
    if make_upper :
        new_text=new_text+i.upper()
        make_upper=False
    else:
        new_text=new_text+i
    if i==" " :
        make_upper=True
print(new_text)
        

Hello Nigger


In [5]:
my_scores= [22,30,[1,2,3]]
print(my_scores[2])

[1, 2, 3]


In [6]:
animals=["dog","cat","rat","fish"]
print(animals[-4])

dog


In [9]:
numbers=[289.358,3958,385,38942,4792]
print(numbers[2:4])

[385, 38942]


In [1]:
import builtins
print(builtins)

<module 'builtins' (built-in)>


In [2]:
print(dir(builtins))

['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BaseExceptionGroup', 'BlockingIOError', 'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 'Ellipsis', 'EncodingWarning', 'EnvironmentError', 'Exception', 'ExceptionGroup', 'False', 'FileExistsError', 'FileNotFoundError', 'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError', 'None', 'NotADirectoryError', 'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning', 'PermissionError', 'ProcessLookupError', 'PythonFinalizationError', 'RecursionError', 'ReferenceError', 'ResourceWarning', 'RuntimeError', 'RuntimeWarning

In [3]:
n=input("whats your name?")
x=input("whats your age?")

whats your name? prateek
whats your age? 24


In [4]:
oct??


Signature: oct(number, /)
Docstring:
Return the octal representation of an integer.

>>> oct(342391)
'0o1234567'
Type:      builtin_function_or_method

In [5]:
exam_scores=[85,92,78,90,88,95,82,79,87,91]
def calculate_exam_statistics(exam_scores):
    num_students=len(exam_scores)
    average_score=sum(exam_scores)/num_students
    highest_score=max(exam_scores)
    lowest_score=min(exam_scores)
    num_passed=0
    num_failed=0
    for i in exam_scores:
        if i>=80:
            num_passed=num_passed+1
        else:
            num_failed=num_failed+1
    return average_score,highest_score,lowest_score,num_passed,num_failed
    

In [6]:
calculate_exam_statistics(exam_scores)

(86.7, 95, 78, 8, 2)

In [9]:
name=input("enter the name")
rev_string="" 
for i in name:
    rev_string=rev_string+i
print (rev_string)

enter the name don


don


In [8]:
text = "hello"
reversed_text = ""

for letter in text:
    reversed_text = letter + reversed_text

print(reversed_text)

olleh


In [3]:
def my_function():
    print("the payment due is next week")
    print("kindly pay immedieately")

In [ ]:
for i in range(3):
    a=input("enter your name")
    b=int(input("enter the units of eetricity consumed"))
    bill=b*10
    print("the total bill is ",bill)
    my_function()

In [7]:
def find_max(num1,num2,num3):
    num1=int(input("enter the number"))
    num2=int(input("enter the number"))
    num3=int(input("enter the number"))
    x=max(num1,num2,num3)
    print("the highest no is" ,x)
             

In [8]:
find_max(3,5,8)

enter the number 3
enter the number 8
enter the number 10


the highest no is 10


In [1]:
a=[23,24,25,30,40,59]
print(len(a))

6


In [3]:
a=[23,24,25,30,40,59]
print(a[-6:-4])

[23, 24]


In [12]:
scores=[55,89,76,65,93,50,72]
new_scores=[ ]
for i in scores:
    if i>70:
        new_scores.append(i)
    else:
        pass
print(new_scores)
    

[89, 76, 93, 72]


In [19]:
given_list=[1,2,3,4,5,6,7,8,9,10]
x=given_list[0:5]
sum=0
for i in x:
    sum=sum+i
print(sum)

15


In [26]:
given_list=[1,2,3,4,5,6,7,8,9,10]
x=given_list[-1::-1 ]
print(x)

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


In [4]:
numbers=[1,2,3,4,5,6,7,8,9,10]
x=numbers[:5]
y=numbers[5:]
print(y+x)
s=sum(numbers[-2:])
print(s)

[6, 7, 8, 9, 10, 1, 2, 3, 4, 5]
19


In [1]:
numbers=[1,2,3,4,5,6,7,8,9,10]
s=sum(numbers[-2:])
print(s)

19


In [8]:
responses=["yes","","no","","maybe","","","yes","no"]
empty=[]
for i in responses:
    if i !="":
        empty.append(i)
    else:
        pass
print(empty)

['yes', 'no', 'maybe', 'yes', 'no']


In [1]:
class1_scores=[85,90,88,92,78]
class2_scores=[75,82,80,85,79]
sum1=sum(class1_scores)
sum2=sum(class2_scores)
s1=len(class1_scores)
s2=len(class2_scores)
avg_1=sum1/s1
avg_2=sum2/s2
print("the average of class1 is",avg_1)
print("the average of class2 is",avg_2)

the average of class1 is 86.6
the average of class2 is 80.2


In [9]:
sentences=["hello world","pyhton is awesome","i love coding"]
a=sentences[0]
b=sentences[1]
c=sentences[2]
print(a+"\n")
print(b+"\n")
print(c+"\n")

hello world

pyhton is awesome

i love coding



In [7]:
data_points=[10,20,30,40,50]
data_points.append(60)
print(data_points)
data_points.remove(30)
print(data_points)
data_points[0]=5
print(data_points)

[10, 20, 30, 40, 50, 60]
[10, 20, 40, 50, 60]
[5, 20, 40, 50, 60]


In [17]:
students=int(input("enter the no of students"))
new_list=[]
for student in range(students):
    total_credits=int(input("enter the total credits"))
    if total_credits>=12:
        new_list.append(total_credits)
        print("full time")
    else:
        print("part time")
    
       
        
    print(new_list)
         
    
        

enter the no of students 3
enter the total credits 12


full time
[12]


enter the total credits 13


full time
[12, 13]


enter the total credits 14


full time
[12, 13, 14]


In [10]:
num_people=int(input("enter the total no of people"))
age=[]
for i in range(num_people):
    age.append(i)
    print(age)
age_group=[]
for i in age:
    x=int(input("enter the age"))
    print(age_group)
    if x<18:
        print("this is a child")
    elif 18<=x<65:
        print("this is a grown ahh man")
    elif x>=65:
        print("rest in peace mahn")
    else:
        pass
     
    age_group.append(x)
print(age_group)
    
    

enter the total no of people 3


[0]
[0, 1]
[0, 1, 2]


enter the age 45


[]
this is a grown ahh man


enter the age 67


[45]
rest in peace mahn


enter the age 89


[45, 67]
rest in peace mahn
[45, 67, 89]


In [5]:
x="helloworld"
y=x.upper()
print(y)
z=y.split()
print(z)
w='\n'.join(z)
print(w)

HELLOWORLD
['HELLOWORLD']
HELLOWORLD


In [6]:
x="hello world"
y=[]
for i in x:
    y.append(i)
print(y)

['h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd']


In [15]:
ages=[23,12,56,34,2]
ages.sort()
print(ages)
ages.reverse()
print(ages)




[2, 12, 23, 34, 56]
[56, 34, 23, 12, 2]


In [32]:
x=[2,88,45,3,11,90,42]
y=[3,67,45,12,90,44,66]
z=x+y
z.sort()
print(z)
clean=[]
for i in z:
    if i not in clean:
        clean.append(i)
    else:
        pass
print(clean)
        

[2, 3, 3, 11, 12, 42, 44, 45, 45, 66, 67, 88, 90, 90]
[2, 3, 11, 12, 42, 44, 45, 66, 67, 88, 90]


In [5]:
a=[2,12,1,22,13]
mid=len(a)//2
first_half=a[:mid]
second_half=a[mid:]
print(first_half)
print(second_half)

[2, 12]
[1, 22, 13]


In [8]:
a=[2,4,71,13,22,88]
b=[90,76,13,88,34]
clean=[]
for i in a and b:
    if i in a and b:
        clean.append(i)
    else:
        pass
print(clean)
    

[13, 88]


In [1]:
a = [2, 3, 4, 5, 67, 78]
y = a[::2]
print(y)
total = sum(y)
print(total)



[2, 4, 67]
73


In [1]:
def flatten(numbers):
    result=[]
    for i in numbers:
        for j in i:
            result.append(j)
    print(result)

In [2]:
num=[[1,2],[3,4],[5,6]]
flatten(num)

[1, 2, 3, 4, 5, 6]


In [3]:
num=(5,)
print(type(num))

<class 'tuple'>


In [4]:
num=([2,3,6.6],["lebron","kobe","iverson"])
print(type(num))

<class 'tuple'>


In [5]:
q=[1,2,4,"hello"]
w=tuple(q)
print(w)

(1, 2, 4, 'hello')


In [6]:
s="hello"
print(tuple(s))

('h', 'e', 'l', 'l', 'o')


In [7]:
dict_example={'a':2,'q':3,'r':69}
print(tuple(dict_example))

('a', 'q', 'r')


In [8]:
set_exam={23,45,12,56,34,78}
print(tuple(set_exam))

(34, 23, 56, 12, 45, 78)


In [4]:
x=("banana","apple","dragonfruit",23.4)
print(x[-1])
print(x[-3])

23.4
apple


In [11]:
m=(2,3,4,5,6)
print(m[::])
print(m[-2:-5])
print(m[-3::])
print(m[::-3])
print(m[:-3:])

(2, 3, 4, 5, 6)
()
(4, 5, 6)
(6, 3)
(2, 3)


In [13]:
s=[2,3,4,5,6,7,4,7,7,8,9,0]
print(s)

[2, 3, 4, 5, 6, 7, 4, 7, 7, 8, 9, 0]


In [4]:
sentence=["hello","world"]
s=' '.join(sentence)
print(s)

hello world


In [2]:
a=(12,54,64,77,12,3,5,34,12)
b=a.count(12)
print(b)

3


In [5]:
a=('prateek','lebron','prateek','kyrie','anthony edwards','prateek')
i=list(a)
print(i)
i.append('wembanyama')
print(i)
s=tuple(i)
print(s)

['prateek', 'lebron', 'prateek', 'kyrie', 'anthony edwards', 'prateek']
['prateek', 'lebron', 'prateek', 'kyrie', 'anthony edwards', 'prateek', 'wembanyama']
('prateek', 'lebron', 'prateek', 'kyrie', 'anthony edwards', 'prateek', 'wembanyama')


In [1]:
 a=(12,34,12,54,67,45,89)
print(list(a))

[12, 34, 12, 54, 67, 45, 89]


In [9]:
tup1=('pyhton','java','data siece','artificial intelligence')
y=(23,)
tup2=tup1+y
print(tup2)

('pyhton', 'java', 'data siece', 'artificial intelligence', 23)


In [5]:
fruits=('apple','banana','orange','watermelon','kiwi')
q=list(fruits)
print(q)
q.remove('banana')
print(tuple(q))

['apple', 'banana', 'orange', 'watermelon', 'kiwi']
('apple', 'orange', 'watermelon', 'kiwi')


In [7]:
shows=('got','breaking bad',34,69,'snowfall')
y=list(shows)
y[2]='narcos'
print(tuple(y))

('got', 'breaking bad', 'narcos', 69, 'snowfall')


In [10]:
q=(12,67,34,15,99)
print(q*2)

(12, 67, 34, 15, 99, 12, 67, 34, 15, 99)


In [11]:
t=(1,)
l=list(t)
print(l)
print(type(l))

[1]
<class 'list'>


In [5]:
x=(2,4,6,8,9)
print(max(x))
print(min(x))

9
2


In [6]:
y=("train","bus","bike","car","bike")
print(y.count("bike"))

2


In [7]:
z=(34,67,69,22,90)
print(z.index(22))

3


In [9]:
x=(2,3,4,5,6,7)
y=("nba","sga","usa","lakers in five")
print(x+y)

(2, 3, 4, 5, 6, 7, 'nba', 'sga', 'usa', 'lakers in five')


In [10]:
x=(34,89,47,33)
y=list(x)
y.append(69)
print(tuple(y))

(34, 89, 47, 33, 69)


In [11]:
p=(2,3,4,5)
print(sum(p))

14


In [12]:
def total(tup):
    print(sum(tup))

In [14]:
tup1=(1,2,3,4,5)
total(tup1)


15


In [18]:
def reverse(tup):
    print(tup[::-1])

In [19]:
tup1=(2,4,1,5,6,3,6,4,6,2,9)
reverse(tup1)

(9, 2, 6, 4, 6, 3, 6, 5, 1, 4, 2)


In [21]:
def even_odd(numbers):
    for i in numbers:
        if i%2==0:
            print("the no is even",i)
        else:
            print("it is odd",i)

In [22]:
x=(1,2,6,8,3,11,19,66,100)
even_odd(x)

it is odd 1
the no is even 2
the no is even 6
the no is even 8
it is odd 3
it is odd 11
it is odd 19
the no is even 66
the no is even 100


In [23]:
def middle_element(numbers):
    start_mid=len(numbers)//3
    mid_end=2*len(numbers)//3
    middle_term=numbers[start_mid:mid_end]
    print(middle_term)

In [25]:
x=(1,2,3,4,5,6,7,8,9)
middle_element(x)

(4, 5, 6)


In [38]:
def common_elements(x,y):
    empty=[]
    for i in x and y:
        if i in x and y:
            empty.append(i)
    print(tuple(empty))

In [39]:
x=(1,2,3,4)
y=(2,3,5,6)
common_elements(x,y)

(2, 3)


In [10]:
x=set((23,98,67,33,28))
print(x)

{33, 98, 67, 23, 28}


In [9]:
y=set()
print(type(y))

<class 'set'>


In [12]:
x=['lebron',23,6,'miami','lebron',6,'caviliers',23]
print(set(x))

{6, 'miami', 'lebron', 23, 'caviliers'}


In [13]:
x={2,4,1,5,6}
print(x)

{1, 2, 4, 5, 6}


In [14]:
x={1,2,"prateek",7.5,("lebron",23)}
print(x)

{1, 2, 7.5, ('lebron', 23), 'prateek'}


In [18]:
x={2.4,"hello"}
print(x)
   

{'hello', 2.4}


In [20]:
x=[1,2,4,2,"cavs",3,1,"cavs"]
y=set(x)
print(y)    #this is the use of sets, to remove the duplicates in list or any other element.

{1, 2, 3, 4, 'cavs'}


In [2]:
a={"prateek","lebron",45.966,1,89.4,True,99,0,"cavs",False}
print(a)

{'lebron', 1, 0, 99, 'prateek', 45.966, 'cavs', 89.4}


In [5]:
a={"prateek","lebron",45.966,1,89.4,True,99,0,"cavs",False}
print("prate" in a)

False


In [8]:
w={1,"lakers","grizzlies","timberwolves",78,33,34,1,77,45,33}
print(len(w))    # the duplicates are excluded 

9


In [10]:
q={"cavs",23,6,"knincks",11,29,23,11}
q.add(34)
print(q)

{34, 'knincks', 'cavs', 6, 23, 11, 29}


In [11]:
a={"nba","usa","sga"}
b={23,66,82,23,"usa"}
a.update(b)
print(a)

{66, 82, 23, 'usa', 'sga', 'nba'}


In [13]:
a={66, 82, 23, 'usa', 'sga', 'nba',23}
a.remove("usa")
print(a) #

{66, 82, 23, 'sga', 'nba'}


In [15]:
a={21,67,34,56,67,99,32}
c=a.pop()
print(c)
print(a)

32
{34, 67, 99, 21, 56}


In [17]:
x={"lebron","luka","anthony edwards"}
y={23,20,11}
z=x.union(y)
print(z)

{'lebron', 'anthony edwards', 20, 23, 'luka', 11}


In [18]:
x={"lebron","luka","anthony edwards"}
print(max(x))

luka


In [20]:
y={23,20,11,2,78,82,31,22}
x=max(y)
print(x)

82


In [24]:
x={"knicks","lakers","heat","okc"}
y={"heat","lakers","bucks","spurs"}
z=x.intersection(y)
print(z)

{'heat', 'lakers'}


In [25]:
x={"knicks","lakers","heat","okc"}
y={"heat","lakers","bucks","spurs"}
diff1=x.difference(y)
diff2=y.difference(x)
print(diff1)
print(diff2)

{'knicks', 'okc'}
{'bucks', 'spurs'}


In [9]:
students_passed_maths={101,102,103,104,105}
students_passed_science={103,104,105,106,107}
both_pass=students_passed_science.intersection(students_passed_maths)
print(both_pass)
print(len(both_pass))
maths=students_passed_maths.difference(students_passed_science)
print(maths)
science=students_passed_science.difference(students_passed_maths)
print(science)
sub=students_passed_maths.issubset(students_passed_science)
print(sub)
sup=students_passed_science.issuperset(students_passed_maths)
print(sup)

{104, 105, 103}
3
{101, 102}
{106, 107}
False
False


In [13]:
x={23,25,89,90,78}
x.discard(25)
print(x)
x.add(69)
print(x)

{23, 89, 90, 78}
{69, 23, 89, 90, 78}


In [2]:
X=[1,3,2,4,5,6,7]
X.remove(3)
print(X)

[1, 2, 4, 5, 6, 7]


In [4]:
x={21,67,21,89,99}
y={"lebron","kyrie","brunson"}
x.update(y)
print(x)
print(len(y))

{'kyrie', 'brunson', 67, 99, 21, 'lebron', 89}
3


In [5]:
x={21,67,21,89,99}
y={"lebron","kyrie","brunson"}
print(x.union(y))

{'kyrie', 'brunson', 67, 99, 21, 'lebron', 89}


In [7]:
q={2,1,45,34,2,89}
c={44,2,89,67,90}
print(c.intersection(q))

{89, 2}


In [4]:
x={"name":"Prateek" ,"age": 36,"length":"dk"}
print(x)

{'name': 'Prateek', 'age': 36, 'length': 'dk'}


In [2]:
contact={"alice":"91067873","chad":9022378,"ezeikel":902783}
print(contact)

{'alice': '91067873', 'chad': 9022378, 'ezeikel': 902783}


In [6]:
mixed_dict={"name":"PRATEEK","courses":["science","maths","sst"],"address":{"country":"India","state":"karnataka","zipcode":2893}}
print(mixed_dict)

{'name': 'PRATEEK', 'courses': ['science', 'maths', 'sst'], 'address': {'country': 'India', 'state': 'karnataka', 'zipcode': 2893}}


In [8]:
matches=dict(first_match="okc loss",second_match="lakers win",finals="spurs for the win")
print(matches)

{'first_match': 'okc loss', 'second_match': 'lakers win', 'finals': 'spurs for the win'}


In [9]:
person={"name":"prateek","country":"india","city":"karwar"}
print(person)

{'name': 'prateek', 'country': 'india', 'city': 'karwar'}


In [10]:
squares={x:x*x for x in range(6)}
print(squares)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25}


In [12]:
names=["kohli","bumrah","rohit","yadav"]
upper={name:name.upper() for name in names}
print(upper)

{'kohli': 'KOHLI', 'bumrah': 'BUMRAH', 'rohit': 'ROHIT', 'yadav': 'YADAV'}


In [16]:
for i in range(6):
    i=i**2
    print(i)

0
1
4
9
16
25


In [19]:
names=["prateek","lebron","rose"]
upper={name:name.upper() for name in names}
print(upper)

{'prateek': 'PRATEEK', 'lebron': 'LEBRON', 'rose': 'ROSE'}


In [12]:
def inventory():
    products={}
    for i in range(3):
        product_id=int(input("enter the id"))
        product_name=input("enter the name")
        products.update({product_id:product_name})
    print(products)



In [13]:
inventory()

enter the id 2
enter the name nike
enter the id 3
enter the name adidas
enter the id 5
enter the name nykaa


{2: 'nike', 3: 'adidas', 5: 'nykaa'}


In [2]:
def inventory(num_products):
    num_products=int(input("enter the no of products"))
    products={}
    for i in range(1,num_products+1):
        product_id=int(input("enter the prodcuct id"))
        product_name=input("enter the product name")
        products[product_id]=product_name
    return products

In [6]:
inventory(2)

enter the no of products 4
enter the prodcuct id 23
enter the product name plr
enter the prodcuct id 345
enter the product name moo
enter the prodcuct id 34
enter the product name ef
enter the prodcuct id 90
enter the product name kfe


{23: 'plr', 345: 'moo', 34: 'ef', 90: 'kfe'}

In [1]:
x={"player1":"lebron","player2":"kyrie","player3":"jordan"}
y=x["player2"]
print(y)

kyrie


In [2]:
character={"name":"lebronjames","age":40,"height":177}
print(character["height"])

177


In [4]:
classroom={"name":"prateek","marks":90,"name":"anish","marks":92}
print(classroom)

{'name': 'anish', 'marks': 92}


In [7]:
custom={(1,2,3):"prateek","age":45,2235:"adidas"}
print(custom)

{(1, 2, 3): 'prateek', 'age': 45, 2235: 'adidas'}


In [9]:
custom={(1,2,3):"prateek","age":45,2235:"adidas"}
print(2235 in custom)

True


In [10]:
record={"name":"prateek","age":(23,43,55),"dict":{2,3,4,5,6}}
print(record)    #keys cannot be mutable ,only immutable objects(tuples,integers,floating point,strings)
#,but vvalues can be anything(lists,tuples,dictionaries,sets,lists,integer,floating,strings)

{'name': 'prateek', 'age': (23, 43, 55), 'dict': {2, 3, 4, 5, 6}}


In [13]:
typeshii={(34,2,4,5):(4,5,3,5,"prateek"),("l","p"):(23,43,55),"dict":{2,3,4,5,6}}
print(typeshii)

{(34, 2, 4, 5): (4, 5, 3, 5, 'prateek'), ('l', 'p'): (23, 43, 55), 'dict': {2, 3, 4, 5, 6}}


In [2]:
employees={
    "dlf":{"name":"prateek","age":25,"perfromance":"good"},
    "ibm":{"name":"prateek","age":25,"performance":"excellent"}
}
print(employees["ibm"]["name"])
print(employees["dlf"]["perfromance"])

prateek
good


In [7]:
book_ratings={"python programming":4.5,"data science handbook":4.8,"machine learning basics":4.2}
if "python programming" in book_ratings:
    print("found")
else:
    print("not found")
titles=list(book_ratings.keys())
print(titles)



found
['python programming', 'data science handbook', 'machine learning basics']


In [14]:
fruit_stock={"apple":10,"banana":15,"orange":8,"grape":20}
for i in fruit_stock:
    print("fruits:",i,",stocks:",fruit_stock[i])
   

fruits: apple ,stocks: 10
fruits: banana ,stocks: 15
fruits: orange ,stocks: 8
fruits: grape ,stocks: 20


In [4]:
p=[2,3,1,7,4,3,"prateek"]
for index,elements in enumerate(p):
    print(f"the index is {index} and the element is {elements}")

the index is 0 and the element is 2
the index is 1 and the element is 3
the index is 2 and the element is 1
the index is 3 and the element is 7
the index is 4 and the element is 4
the index is 5 and the element is 3
the index is 6 and the element is prateek


In [5]:
shows={'hit':"seven","flop":9,"good":"fight club"}
print(len(shows))

3


In [13]:
a={"first match":"cavs","second":"knicks","average":99.34}
print(list(a.keys()))
print(list(a.values()))

['first match', 'second', 'average']
['cavs', 'knicks', 99.34]


In [16]:
p={1:23,2:345,"quality":"very good"}
p[2]="bharat"
print(p)

{1: 23, 2: 'bharat', 'quality': 'very good'}


In [25]:
b={1:"poor",2:9.3,3:"very good"}
b.update({4:56.4,"perfomance":45})
print(b)

{1: 'poor', 2: 9.3, 3: 'very good', 4: 56.4, 'perfomance': 45}


In [29]:
c={1:"samsung",2:"max",3:"audermas piguet",4:"louis vuitton"}
del c[2],c[4]
print(c)


{1: 'samsung', 3: 'audermas piguet'}


In [30]:
e={1:"cheetah",2:"lion",3:"jaguar"}
e.pop(2)
print(e)

{1: 'cheetah', 3: 'jaguar'}


In [31]:
e[1]="kangaroo"
print(e)

{1: 'kangaroo', 3: 'jaguar'}


In [32]:
e.clear()
print(e)

{}


In [8]:
x={1:"good",2:"very good",3:"excellent"}
y={4:"prateek",5:"jalen",6:"james"}
n={}
for d in (x,y):
    n.update(d)
print(n)
    

{1: 'good', 2: 'very good', 3: 'excellent', 4: 'prateek', 5: 'jalen', 6: 'james'}


In [11]:
dic_empty={}
for i in range(1,15):
    dic_empty[i]=i**2
print(dic_empty)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196}


In [24]:
z={}
d={i:i**2 for i in range(1,15)}
z.update(d)

print(z)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196}


In [6]:
c={1:"good",2:44.3,3:"very good",4:78.34}
for i in c:
    if c[i]==44.3:
        ##the difference between '=' and '==' is that, '=' is for assigning the value,'=='is looklike
        print("present")
    else:
        print("not found")

not found
present
not found
not found


In [7]:
z={1:"good",2:"lebron",3:"kyrie",4:334.2}
def is_present(value):
    if value in z: # the "in" keyword only works on keys in case of dictionaries.
        print("found")
    else:
        print("not found")

In [8]:
is_present(4)

found


In [1]:
## OOPS starting here

In [9]:
class calculator:      ##you are creating a class here (calculator)
    def add_number(self,a,b):
        print(a+b)                  ##you are explaining what the calucltor must do (add_number ,diff)
    def difference_number(self,a,b): #"self" is for saying that the function(differernce_number)
                                     ## is binded to the above class(calculator)
        print(a-b)

In [10]:
calci = calculator()  ##you are creating a object(calci) here using the above class(calculator)


In [11]:
calci.add_number(2,4)
calci.difference_number(9,1)

6
8


In [3]:
class car:
    def start(self):
        print(f"the {self.color} {self.brand} is starting")
    ## the .color and .brand have to be declared when creating the object(car1 and car2)

   
        

In [4]:
car1=car()
car1.color="red"
car1.brand="bmw"
car1.start()
car2=car()
car2.color="yellow"
car2.brand="audi"
car2.start()

the red bmw is starting
the yellow audi is starting


In [11]:
class form: #creating a blank form here 
    def details(self):
        print(f"name={self.name}") ## mentioning what needs to be filled in the blank form(name,age)
        print(f"age={self.age}")
        

In [12]:
f1=form()  #creating an object to fill the blank form with te name and age
f1.name="prateek"
f1.age=25
f1.details()## finally calling out the function to fill the form with the created object

name=prateek
age=25


In [3]:
class room:
    def __init__(self,marks,grades):
        self.marks=marks
        self.grades=grades
    
    def performance(self):
        print("the grades are: ",self.grades)
        print("the marks are: ",self.marks)
        

In [4]:
s1=room("d",45)

s1.performance()

the grades are:  45
the marks are:  d


In [9]:
class Game():
    def __init__(self, Character, Age):
        self.Character = Character
        self.Age = Age

    def score(self):
        if self.Age >= 18:
           print("wow")
        else:
           print("goodbye")




In [11]:
random_player=Game('male',19)
random_player.score()
print(random_player.Age) ##  instead of (self.character) ,since the object
#is already declared(random_player), you have to mention (random_player.character) in print.

wow
19


In [9]:
class dog:
    def __init__(self,name,breed="husky",age=1):
        self.name=name
        self.breed=breed
        self.age=age                       
    def bark(self):
        print(f"this {self.breed} is barking with the {self.name}, and aged {self.age}")
        
    

In [10]:
D1=dog("micheal") #here breed="husky" and age=1 are taken as default values and 
D2=dog("john")#once you have given the new values the default gets overwritten
D1.bark()
D2.bark()

this husky is barking with the micheal, and aged 1
this husky is barking with the john, and aged 1


In [1]:
class players:
    def __init__(self,name,points):
        self.name=name
        self.points=points
    def performance(self,total):
        if total>20:
            if self.points>20:
                 print("mvp candidate")
            total=total+self.points
            print(f"this guy scored {total} points in his carrer")
           
        else:
            print("not worthy")

In [5]:
p1=players("shai",15)
p2=players("wemby",29)
print(p2.name)
print(p1.name)
p1.performance(2)
p2.performance(67)

wemby
shai
not worthy
mvp candidate
this guy scored 96 points in his carrer


In [7]:
class mvp:
    def win(self):  
        print("the spurs are winning the finals")
class winners:
    def win(self): #same function name but different actions (polymorphism)
        print("the knicks are going till game 7")
        

In [8]:
M=mvp()
W=winners()
W.win() 
M.win()

the knicks are going till game 7
the spurs are winning the finals


In [11]:
class wemby:                    #parent class
    def dunk(self):
        print("he can dunk")
class shai(wemby):                  #child class
    def dunk(self):
        print("he cant dunk")
class lebron(wemby):                #also child class
    def dunk(self):
        print("he is the father of all")

In [13]:
W=wemby()
S=shai()
L=lebron()
L.dunk()
S.dunk()  #even though child class declared using parent class , but the actions are different than parents,
          #means child has overrode the parent class.

he is the father of all
he cant dunk


In [14]:
class calculator:
    def listen(self,*args):
        print(sum(args))
        
        

In [15]:
calci=calculator()
calci.listen(34,78,22,38,90,12)

274


In [1]:
class MediaPlayer:
    def play(self):
        print("here are the songs:eminem,jay-z,kanyewest,drake")
class AudioPlayer(MediaPlayer): 
    def play(self):
        print("only audio playing for this music")
class VideoPlayer(MediaPlayer):
    def play(self):
        print("here is the video for that song")

In [2]:
M=MediaPlayer()
A=AudioPlayer()
V=VideoPlayer()
M.play()
A.play()
V.play()

here are the songs:eminem,jay-z,kanyewest,drake
only audio playing for this music
here is the video for that song


In [1]:
class shape:
    def area(self):
        print("this is the area")
class circle(shape):
    def area(self,r):
        pi=3.14
        a=pi*r**2
        print(f"the area of the circle is {a}")
class rectangle(shape):
    def area(self,l,b):
        A=l*b
        print(f"the area of rectangle is {A}")
        
        

In [2]:
S=shape()
C=circle()
R=rectangle()

In [3]:
S.area()
C.area(2)
R.area(3,4)

this is the area
the area of the circle is 12.56
the area of rectangle is 12


In [5]:
class calculator:
    def add(self,*args):
        print(sum(args))
    def multi(self,*args):
        result=1
        for i in args:
            result=result*i
        print(result)

In [6]:
calci=calculator()
calci.multi(3,2,4,5)

120


In [7]:
class discount:
    def calculate(self,price):
        dis=0.1*price
        print(f"the discount price is {dis}")
    def custom(self,price,D):
        total_discount=price*(0.01*D)
        print("the total discount would be",total_discount)
        

In [8]:
DIS=discount()
DIS.calculate(100)
DIS.custom(210,20)

the discount price is 10.0
the total discount would be 42.0


In [15]:
class father:
    def money(self):
        print("father has money")
    def car(self):
        print("father has a lamborghini")
class son(father):  # child class(son) inherited from parent class(father)
    def money(self):
        print("i have a hayabusa")
    def game(self):
        print("i can play modern wrfare 2019")
        

In [18]:
F=father()
S=son()
S.car()
S.money()


father has a lamborghini
i have a hayabusa


In [1]:
class parent:
    def lebron(self):                              #single inheritance
        print("i am the king")
class son(parent):
    def bronny(self):
        print("i am the new king")
    

In [3]:
P=parent()
S=son()
S.lebron()
S.bronny()

i am the king
i am the new king


In [9]:
class grandfather():
    def money(self):
        print("i got money")
class father(grandfather):
    def house(self):
        print("I have a son")
class son(father):                                      ## multilevel inheritance
    def play(self):
        print("i can play everything")

In [10]:
S=son()
S.money()
S.house()
S.play()
f=father()
f.money()
f.house()

i got money
I have a son
i can play everything
i got money
I have a son


In [18]:
class dad:
    def bike(self):
        print("i have a bike")
class mom:                                      ## MULTIPLE INHERITANCE
    def food(self):
        print("i can make good food")
class son(mom,dad):
    def play(self):
        print("i play basketball")

In [20]:
S=son()
S.food()
S.bike()
S.play()

i can make good food
i have a bike
i play basketball


In [26]:
class father:
    def money(self):
        print(" i have money")
class son(father):
    def talk(self):                          ## hierarchial inheritance
        print("i can speak")
class daughter(father):
    def speak(self):
        print("i cant speak")

In [33]:
S=son()
D=daughter()

S.money()
D.money()

 i have money
 i have money


In [1]:
class A:
    def feature1(self):
        print("this is feature 1")
class B(A):
    def feature2(self):
        print("this is feature 2")
class C(A):
    def feature3(self):
        print("this is feature 3")
class D(B,C):
    def feature4(self):
        print("this is feature 4")

In [5]:
a=A()
b=B()
c=C()
d=D()
b.feature1()
d.feature2()
c.feature1()

this is feature 1
this is feature 2
this is feature 1


In [1]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])
print(arr)
print(len(arr))
print(type(arr))

[1 2 3 4 5]
5
<class 'numpy.ndarray'>


In [8]:
a=np.array(69)  #0 dimensional array: only one element inside arrra*(
print(a.ndim)

0


In [13]:
q=np.array([[[1,2],[4,2]],[['hello','world'],['lets','go']],[[25.7,45.6],[89,93.12]]])
print(q.ndim)
print(q)         #3d array

3
[[['1' '2']
  ['4' '2']]

 [['hello' 'world']
  ['lets' 'go']]

 [['25.7' '45.6']
  ['89' '93.12']]]


In [4]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr2=arr.shape
print(arr2)

(10,)


In [2]:
import numpy as np
arr=np.linspace(0,10,5) ## np.linspace(start,stop,numbers between them)
print(arr)

[ 0.   2.5  5.   7.5 10. ]


In [3]:
q=np.random.rand(3)
print(q)

[0.46627331 0.87539145 0.50675868]


In [5]:
e=np.eye(4)
print(e.shape)  #returns the no of rows and columns.

(4, 4)


In [7]:
q=np.array([1,2,3,4,5]).dtype
print(q)

int64


In [14]:
r=np.array([[1,2,3],[5,6,7,4]]).reshape(7,1)
print(r) # cant have unequal no of elements in the array

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [11]:
import numpy as np
r=np.array([[1,2,3],[38,45,4]]).transpose()
print(r)

[[ 1 38]
 [ 2 45]
 [ 3  4]]


In [13]:
import numpy as np
q=np.array([[2,3,5,6],[8,4,7]]).reshape()
print(q)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [18]:
import numpy as np
arr1=np.array([[1,2,3,4],
              [3,6,9,12]])
arr2=np.array([[[1,2,3,45]]])
S=np.subtract(arr1,arr2)
print(abs(S))
            


[[[ 0  0  0 41]
  [ 2  4  6 33]]]


In [20]:
arr=np.divide([4,6,9],[2,3,4])
print(arr)

[2.   2.   2.25]


In [21]:
arr=np.array([2,3,4,5])
r=np.power(arr,4)
print(r)

[ 16  81 256 625]


In [4]:
import numpy as np
arr=np.median([[1,2,3],  ## median() will convert any dimension into 1d array first, then calculates median
              [4,5,6]])    # median=3+4/2=3.5
print(arr)


3.5


In [5]:
n=np.std([[2,4,6,8],
             [1,3,5,7]])
print(n)
             

2.29128784747792


In [7]:
p=np.percentile([[[2,3,4,5,6],
                  [3,4,5,1,7]]],25)
print(p)
                  

3.0


In [10]:
q=np.percentile([1,2,3,4],50)
print(q)

2.5


In [3]:
import numpy as np
e=np.array([[1,2,3,4]])
r=np.array([[40,20,10,30]])
print(np.corrcoef(e,r))

[[ 1.  -0.4]
 [-0.4  1. ]]


In [5]:
import numpy as np
q=np.array([[2,3,4,5],
             [5,6,7,8]])
w=np.array([67,34,12,56],[89,99,23,1])## you cant do this for any numpy operation ,while declaring you need
print(np.corrcoef(q,w))## to have same no or rows in both the arrays,q has 2d shape and easch row has
## 4 elements , but w is completely wwong , it is neither 1 d nor 2 d nor 3d , so the error is popping up.

TypeError: Field elements must be 2- or 3-tuples, got '89'

In [8]:
import numpy as np
e=np.array([2,3,4,5],## cant do this
           [4,2,8,9])
w=np.array([[2,3,4,5], # either do this or 3d 
            [4,5,6,7]])
print(e)

TypeError: Field elements must be 2- or 3-tuples, got '4'

In [11]:
import numpy as np
e=np.array([[2,3,4,5],
           [4,2,8,9]])
w=np.array([[2,3,4,5], 
            [4,5,6,7]])
print(np.corrcoef(e,w))  ## the output means both the arays ir datasets are closely related t each other
## as everything is within 1.

[[1.        0.8205379 1.        1.       ]
 [0.8205379 1.        0.8205379 0.8205379]
 [1.        0.8205379 1.        1.       ]
 [1.        0.8205379 1.        1.       ]]


In [12]:
a=np.corrcoef([1,2,3],[5,6,7])
print(a)

[[1. 1.]
 [1. 1.]]


In [15]:
import numpy as np
e=np.array([1,2,3,4,5])
r=np.array([3,4,5,6,1])
print(np.add(e,r))

[ 4  6  8 10  6]


In [11]:
import numpy as np
r=np.array([[[2,4,6,8],
            [1,3,5,7]]])  #r[0] will print both the arrays as it is , r[0][0] will go to the first array
# which is [2 4 6 8]
print(r[0][0])

[2 4 6 8]


In [12]:
import numpy as np
r=np.array([[[2,4,6,8],
            [1,3,5,7]]])
print(r[0][0][1:3]) #means go to both the arrays then go to first one and slice it from [1:3]

[4 6]


In [16]:
f=np.array([[[2,3,4,5,6]]])
print(f[0][1:3])

[]


In [30]:
t=np.array([[2,3,4,7,6],
            [7,8,2,1,4]])
print(t[t>2]) #means you are filtering out the elements inside t that are greater than 2 

[3 4 7 6 7 8 4]


In [3]:
import numpy as np
r=np.array([1,23,45,12,67,11,10,8,46,69])
print(np.where([r%2==0]))   ## can have any conditions inside the bracket.(==,> <,%)

(array([0, 0, 0, 0]), array([3, 6, 7, 8]))


In [6]:
r=np.array([[[1,23,45,12,67],[11,10,8,46,69]]])
print(np.where([r>10]))

(array([0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0, 0, 0]), array([0, 0, 0, 0, 1, 1, 1]), array([1, 2, 3, 4, 0, 3, 4]))


In [8]:
import numpy as np
t=np.array([[2,3,4,5,6],
            [1,4,2,56,7]])
print(np.argmax(t))
print(np.argmin(t))

8
5


In [24]:
import numpy as np
v=np.array([[[2,3,4,5],
             [1,4,2,7]]])
r=np.array([[[1,2,3,4],
            [4,3,6,1]]])
print(np.hstack((v,r)))


[[[2 3 4 5]
  [1 4 2 7]
  [1 2 3 4]
  [4 3 6 1]]]


In [26]:
import numpy as np
t=np.array([[[2,3,4,5],
             [1,4,2,7]]])
s=np.array([[[1,2,3,4],
            [4,3,6,1]]])
print(np.concatenate((t,s)))

[[[2 3 4 5]
  [1 4 2 7]]

 [[1 2 3 4]
  [4 3 6 1]]]


In [1]:
import numpy as np
arr1=np.array([[[4,3,5],
                [6,2,1],
                [7,9,6]]])
print(arr1)

[[[4 3 5]
  [6 2 1]
  [7 9 6]]]


In [2]:
n=np.array([[[4,6,3],[5,64,34]],[[6,5,4],[9,6,2]]])
print(n)

[[[ 4  6  3]
  [ 5 64 34]]

 [[ 6  5  4]
  [ 9  6  2]]]


In [3]:
p=np.array([[[[[3,4,5],
               [4,2,1]]]],[[[[9,3,4],[6,2,7]]]]])
print(p)
print(p.ndim)

[[[[[3 4 5]
    [4 2 1]]]]



 [[[[9 3 4]
    [6 2 7]]]]]
5


In [20]:
import numpy as np
n=np.array([[[4,6,3],[5,64,34]],[[6,5,4],[9,6,2]]])
print(n[0,0,0]+n[1,1,2])

6


In [16]:
arr=np.array([[[10,20,30,40,50],[60,70,80,90,100]]])
print(arr[0,0,2])

30


In [22]:
arr=np.array([[2,4,8],[6,12,18]]) ##[2,4,8] is at the index position of 0 and wihtin this 0th element
## 4 is at the index position 2 and to access 12 we can do arr[1,1] 
#means 1st element in the array and element at 1st index within gthat array
print(arr[0,1]+arr[1,2])

22


In [2]:
arr=np.array([[[10,20,30,40,50],[60,70,80,90,100]]])
print(arr[0,1,1:4])

[70 80 90]


In [6]:
n=np.array([[1,2,3]])
print(n)

[[1 2 3]]


In [8]:
import numpy as np
arr=np.array([2,4,6,8,10])
print(arr[::2])

[ 2  6 10]


In [17]:
arr=np.array([[2,4,6,8,10],
              [1,3,5,7,9]])
print(arr[0,::2],arr[1,::2])

[ 2  6 10] [1 5 9]


In [21]:
p=np.array([2,4,5,2,5,2,4,5],dtype='f4')
print(p.dtype)
print(p)

float32
[2. 4. 5. 2. 5. 2. 4. 5.]


In [25]:
u=np.array([[[4,6,7,8]],[[1,3,5,1]]])
print(u.shape)

(2, 1, 4)


In [5]:
import numpy as np
arr1=np.array([[2,3,4,5],[4,5,6,7]])
arr2=np.array([[1,2,3,4],[8,9,2,1]])
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[2 3 4 5]
 [4 5 6 7]
 [1 2 3 4]
 [8 9 2 1]]


In [24]:
arr1=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr1,4)
print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [8]:
import numpy as np
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10],[1,3,5,7,8]])
print(np.array_split(arr1,2)) ## for np.split(),total elements%prts divided==0
##np.split() does not allow unequal distribution of elements, but np.array_split() allows it.

[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[1, 3, 5, 7, 8]])]


In [11]:
s=np.array([[[3,4,5,6],[15,12,17,48]],[[21,45,34,78],[33,46,12,89]]])
print(s.ravel())

[ 3  4  5  6 15 12 17 48 21 45 34 78 33 46 12 89]


In [13]:
n=np.array([[[[3,4,5],[4,5,6],[6,79,9]]]])
print(n.shape)

(1, 1, 3, 3)


In [18]:
l=np.array([32,12,6,9,6,2,32,90,8,55,12,6,33,90])
print(np.unique(l,return_index = True,return_counts=True))

(array([ 2,  6,  8,  9, 12, 32, 33, 55, 90]), array([ 5,  2,  8,  3,  1,  0, 12,  9,  7]), array([1, 3, 1, 1, 2, 2, 1, 1, 2]))


In [19]:
r=np.array([5,3,7,2,3,6,3,4])
print(np.delete(r,3))

[5 3 7 3 6 3 4]


In [25]:
t=np.array([[3,4,5],[5,1,2],[6,7,90]])
print(np.delete(t,1,axis=1))

[[ 3  5]
 [ 5  2]
 [ 6 90]]


In [3]:
import numpy as np
r=np.array([[1,2,3],[4,5,6]])[0]
print(r)

[1 2 3]


In [12]:
r=np.array([[[4,5,6,7,9]],[[6,7,8,9,10]]])
print(np.vstack(r))

[[ 4  5  6  7  9]
 [ 6  7  8  9 10]]


In [11]:
arr1=np.array([[2,4,1,5],[4,3,5,1]])
arr2=np.array([[3,2,5,7],[67,45,23,89]])
print(np.concatenate((arr1,arr2))) # the o/p is same as vstack

[[ 2  4  1  5]
 [ 4  3  5  1]
 [ 3  2  5  7]
 [67 45 23 89]]


In [3]:
import pandas as pd
data={"name":["prateek","lebron","kyrie"],"age":[23,34,56]}
df=pd.DataFrame(data)
print(df)

      name  age
0  prateek   23
1   lebron   34
2    kyrie   56


In [6]:
d=[["prateek",20],
   ["lebron",40],
   ["curry",57]]
df=pd.DataFrame(d,columns=["name","cahmpionships"])
print(df)

      name  cahmpionships
0  prateek             20
1   lebron             40
2    curry             57


In [19]:
import pandas as pd 
data={'name':["prateek","lebron","kyrie","curry"],  #dictionaries are most commonly used in pandas
      'trophies':[23,45,12,33]}
df=pd.DataFrame(data)
print(df.isnull())
print(df.dtypes)  
print(df.info())
print("the shape is:",df.shape)
print("here is the stats of the data",df.describe())

    name  trophies
0  False     False
1  False     False
2  False     False
3  False     False
name        object
trophies     int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   name      4 non-null      object
 1   trophies  4 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes
None
the shape is: (4, 2)
here is the stats of the data         trophies
count   4.000000
mean   28.250000
std    14.080128
min    12.000000
25%    20.250000
50%    28.000000
75%    36.000000
max    45.000000


In [23]:
df2=pd.DataFrame({'class':[2024,2023,2022,2021],
                  'players':['brunson','haliburton','edwards','wemby']})
print(df2) #creating  data in one line
print(df2.describe())
print(df2.info())

   class     players
0   2024     brunson
1   2023  haliburton
2   2022     edwards
3   2021       wemby
             class
count     4.000000
mean   2022.500000
std       1.290994
min    2021.000000
25%    2021.750000
50%    2022.500000
75%    2023.250000
max    2024.000000
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   class    4 non-null      int64 
 1   players  4 non-null      object
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes
None


In [2]:
import pandas as pd
df=pd.Series([1,2,3])
print(df)

0    1
1    2
2    3
dtype: int64


In [19]:
df=pd.DataFrame({"name":["lebron","curry","creed","curry"],"age":[23,12,23,12]})
print(df.duplicated())
print(df.drop_duplicates())
print(df.rename(columns={"age":"championships"}),df.drop_duplicates())
print(df.loc[2])
print(df.value_counts())

0    False
1    False
2    False
3     True
dtype: bool
     name  age
0  lebron   23
1   curry   12
2   creed   23
     name  championships
0  lebron             23
1   curry             12
2   creed             23
3   curry             12      name  age
0  lebron   23
1   curry   12
2   creed   23
name    creed
age        23
Name: 2, dtype: object
name    age
curry   12     2
creed   23     1
lebron  23     1
Name: count, dtype: int64


In [1]:
df=pd.DataFrame({"name":["leb","curr","kyr","gianis"],"rings":[6,3,2,1]})
print(df.groupby())

TypeError: You have to supply one of 'by' and 'level'

In [10]:
df=pd.DataFrame({"name":["leb","curr","kyr","gianis"],"rings":[6,3,2,1]})
print(df.sort_values("rings"))
df["ratings"]=[5,5,4,4]
print(df.drop("rings",axis=1)) #mentioning axis is mandatory

     name  rings
3  gianis      1
2     kyr      2
1    curr      3
0     leb      6
     name  ratings
0     leb        5
1    curr        5
2     kyr        4
3  gianis        4


In [4]:
import pandas as pd
df=pd.DataFrame({"name":["leb","tyre","kyr","hali","caitlin"],"rings":[21,3,21,5,3]})
print(df.groupby("rings").sum())


              name
rings             
3      tyrecaitlin
5             hali
21          lebkyr


In [16]:
df=pd.DataFrame({"name":["A","A","B","B"],"age":[8,3,4,1]})
print(df.groupby("name").sum())

      age
name     
A      11
B       5


In [1]:
import pandas as pd
df=pd.DataFrame({"name":["prat","leb","prat"],"rings":[9,4,3]})
print(df.drop_duplicates())

   name  rings
0  prat      9
1   leb      4
2  prat      3


In [2]:
df=pd.DataFrame({"name":["prat","leb","prat"],"rings":[9,4,3]})
print(df.replace("prat","kyr"))

  name  rings
0  kyr      9
1  leb      4
2  kyr      3


In [17]:
import pandas as pd
df=pd.DataFrame({"name":["prat","leb","prat"],"age":[20,21,20]})

print(df.rename(columns={"age":"rings"}))
print(df.value_counts())
print(df.sort_values("name",ascending=False))

   name  rings
0  prat     20
1   leb     21
2  prat     20
name  age
prat  20     2
leb   21     1
Name: count, dtype: int64
   name  age
0  prat   20
2  prat   20
1   leb   21


In [12]:
import pandas as pd
df=pd.DataFrame({"brand":["bmw","lambo","proshce","mazda",],"ratings":[5,6,3,1]})

df["price"]=[23,45,67,12]
print(df)
df.insert(loc=1,column="damage",value=0)##to insert a new column at a particualr  position
df## by mentioning the index no (loc=1) and then the value=0 and column name="damage"

     brand  ratings  price
0      bmw        5     23
1    lambo        6     45
2  proshce        3     67
3    mazda        1     12


,brand,damage,ratings,price
0,bmw,0,5,23
1,lambo,0,6,45
2,proshce,0,3,67
3,mazda,0,1,12


In [5]:
df=pd.read_csv("https://raw.githubusercontent.com/TheiScale/YouTube-Video-Notes/refs/heads/main/Zomato_Python_Project/Zomato%20data%20.csv")
df

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining


In [6]:
df.describe()

,votes,approx_cost(for two people)
count,148.000000,148.000000
mean,264.810811,418.243243
std,653.676951,223.085098
min,0.000000,100.000000
25%,6.750000,200.000000
50%,43.500000,400.000000
75%,221.750000,600.000000
max,4884.000000,950.000000


In [7]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes',
       'approx_cost(for two people)', 'listed_in(type)'],
      dtype='object')

In [8]:
df["name"]

0                      Jalsa
1             Spice Elephant
2            San Churro Cafe
3      Addhuri Udupi Bhojana
4              Grand Village
               ...          
143         Melting Melodies
144          New Indraprasta
145             Anna Kuteera
146                   Darbar
147            Vijayalakshmi
Name: name, Length: 148, dtype: object

In [8]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/TheiScale/YouTube-Video-Notes/refs/heads/main/Zomato_Python_Project/Zomato%20data%20.csv")
a=df["name"][0:5]
l=["first","second","third","fourth","fifth"]
pd.Series(list(a),index=l) #you are inserting your own index no's here

first                     Jalsa
second           Spice Elephant
third           San Churro Cafe
fourth    Addhuri Udupi Bhojana
fifth             Grand Village
dtype: object

In [14]:
df=pd.DataFrame({"index":["first","second","third"],"name":["jalsa","spice","san churro"]})
df1=pd.DataFrame({"name":["prat","kyr","leb"],"rate":[1,2,3]})
c=pd.concat([df,df1])
c #common column names are joined and the remaining columns where data is missing is marked as NaN

,index,name,rate
0,first,jalsa,NaN
1,second,spice,NaN
2,third,san churro,NaN
0,NaN,prat,1.0
1,NaN,kyr,2.0
2,NaN,leb,3.0


In [17]:
m=df*df1  #cant multiply when you have strings in your data or object in your data,but if eveyrthing in data is no then yes.

In [20]:
j=df+df1 # you can add two dataframes the common columns will just combine the data they have (jalsaprat)
j

,index,name,rate
0,NaN,jalsaprat,NaN
1,NaN,spicekyr,NaN
2,NaN,san churroleb,NaN


In [1]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/TheiScale/YouTube-Video-Notes/refs/heads/main/Zomato_Python_Project/Zomato%20data%20.csv")

In [2]:
df

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining


In [3]:
df.drop("rate",inplace=True,axis=1)
df

,name,online_order,book_table,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,775,800,Buffet
1,Spice Elephant,Yes,No,787,800,Buffet
2,San Churro Cafe,Yes,No,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,88,300,Buffet
4,Grand Village,No,No,166,600,Buffet
...,...,...,...,...,...,...
143,Melting Melodies,No,No,0,100,Dining
144,New Indraprasta,No,No,0,150,Dining
145,Anna Kuteera,Yes,No,771,450,Dining
146,Darbar,No,No,98,800,Dining


In [4]:
df.drop(3,inplace=True,axis=0)
df

,name,online_order,book_table,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,775,800,Buffet
1,Spice Elephant,Yes,No,787,800,Buffet
2,San Churro Cafe,Yes,No,918,800,Buffet
4,Grand Village,No,No,166,600,Buffet
5,Timepass Dinner,Yes,No,286,600,Buffet
...,...,...,...,...,...,...
143,Melting Melodies,No,No,0,100,Dining
144,New Indraprasta,No,No,0,150,Dining
145,Anna Kuteera,Yes,No,771,450,Dining
146,Darbar,No,No,98,800,Dining


In [7]:
df.set_index("name",inplace=True)
df

KeyError: "None of ['name'] are in the columns"

In [8]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/TheiScale/YouTube-Video-Notes/refs/heads/main/Zomato_Python_Project/Zomato%20data%20.csv")

In [9]:
df

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining


In [10]:
df.set_index('name',inplace=True)
df

,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
name,,,,,,
Jalsa,Yes,Yes,4.1/5,775,800,Buffet
Spice Elephant,Yes,No,4.1/5,787,800,Buffet
San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...
Melting Melodies,No,No,3.3/5,0,100,Dining
New Indraprasta,No,No,3.3/5,0,150,Dining
Anna Kuteera,Yes,No,4.0/5,771,450,Dining


In [11]:
df.reset_index()

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining


In [6]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/sonwaneshivani/Data-Science-Learning/refs/heads/main/taxonomy.csv")

In [7]:
df

,taxonomy_id,name,parent_id,parent_name
0,101,Emergency,NaN,NaN
1,101-01,Disaster Response,101,Emergency
2,101-02,Emergency Cash,101,Emergency
3,101-02-01,Help Pay for Food,101-02,Emergency Cash
4,101-02-02,Help Pay for Healthcare,101-02,Emergency Cash
...,...,...,...,...
285,111-01-07,Workplace Rights,111-01,Advocacy & Legal Aid
286,111-02,Mediation,111,Legal
287,111-03,Notary,111,Legal
288,111-04,Representation,111,Legal
